### ISSUE TITLE
mirrors.py has problem

### ISSUE THREAD

**Issue by superthin** [jblakeman/apt-select#10]
superthin@myubuntu:~/github/apt-select$ ./apt-select.py -c -t 3 -m one-week-behind
Getting list of mirrors ... done.
Testing 3 mirror(s) [3/3] 100%
Looking up status(es) [0/3] 0%Traceback (most recent call last):
  File "./apt-select.py", line 226, in <module>
    flag_status
  File "/home/superthin/github/apt-select/mirrors.py", line 108, in getInfo
    if "unknown" in status:
TypeError: argument of type 'NoneType' is not iterable

*My Ubuntu version/ edition is Ubuntu 14.04 LTS.*

**Comment by jblakeman** [comment]
It seems the Launchpad page for the third mirror was unable to be parsed for status.  I've added a fix in commit [160fd40](https://github.com/jblakeman/apt-select/commit/160fd404b65afdfec1bfa213d407702ae48434b8) to check first for a NoneType before comparing to a string or list of statuses.  Also, commit [7cc3a3e](https://github.com/jblakeman/apt-select/commit/7cc3a3eb18b88e07fe36121aa12028c3294bb2dd) will provide the Launchpad url for the mirror of which the status was unable to be parsed.

After updating your program with the recent changes (`git pull`), a report back with the mirror url that is unable to be parsed would be appreciated.  Then, I'll be able to better understand why the regex did not match.
