### ISSUE TITLE
NameError: name 'info_size' is not defined

### ISSUE THREAD

**Issue by itd** [jblakeman/apt-select#12]
Just FYI... I cloned master (f7179f1bc5a49e17496f58c1848b85f09cf0c022), ran the script, and got this error:
~~~
# apt-select.py
Getting list of mirrors ... done.
Testing 73 mirror(s) [73/73] 100%
Traceback (most recent call last):
  File "/root/bin/apt-select.py", line 245, in <module>
    if info_size == 0:
NameError: name 'info_size' is not defined
~~~

**Comment by jblakeman** [comment]
I'm having trouble reproducing this error.  It seems the only possible cause is if there were an empty dictionary of latency measurements.  The culprit for no successful round trip measurements could be network latency so high that it exceeds the TCP socket timeout (2.5 seconds).  This script is probably not much use if the machine's latency to all servers is over 2.5 seconds.  In that case, an improvement of < 150 ms would likely be insignificant, and downloads would be a crawl regardless of the server they use.

A check for uncommon connectivity issues has been added in [9ee835d348](https://github.com/jblakeman/apt-select/commit/9ee835d348122d5c5cae90e774aef9e5deb582de).
