### ISSUE TITLE
Running with no arguments fails

### ISSUE THREAD

**Issue by dankegel** [jblakeman/apt-select#13]
$ ./apt-select.py 
Getting list of mirrors ...
done.
Testing 76 mirror(s) [76/76] 100%
Traceback (most recent call last):
  File "./apt-select.py", line 296, in <module>
    if not repo:
NameError: name 'repo' is not defined

**Comment by dankegel** [comment]
So there are two bugs here: 1) bad error message if no repos found in apt.sources.list 2) doesn't handle case where all entries in apt.sources.list use the mirror: syntax rather than http: syntax

**Comment by jblakeman** [comment]
Enhancement for improved error handling has been implemented in commit [beaa2cc](https://github.com/jblakeman/apt-select/commit/beaa2cc51846480f9fc7295df9e021b2ffce277b).

In regards to 2, I'll reference [#2] and reiterate that the sources.list file needs to be in the proper format.  

As specified in `man sources.list`, `deb` and `deb-src` types should be in the format:

    deb [ options ] uri suite [component1] [component2] [...]

Where the currently recognized URI types are:
    file
    cdrom
    http
    ftp
    copy
    rsh
    ssh

Currently, `apt-select` only supports `http` and `ftp`.  `http` is the [only required protocol](https://wiki.ubuntu.com/Mirrors) for every alternative mirror host listed in [mirrors.txt](http://mirrors.ubuntu.com/mirrors.txt).

**Comment by jblakeman** [comment]
Added required format and URI types to README in [00e7d4a](https://github.com/jblakeman/apt-select/commit/00e7d4af0cbe846fa245fa911434c3a01e4c6172)
