### ISSUE TITLE
mirrors.txt only has a single mirror to choose from

### ISSUE THREAD

**Issue by dangpzanco** [jblakeman/apt-select#62]
http://mirrors.ubuntu.com/mirrors.txt only contains a single mirror:
http://archive.ubuntu.com/ubuntu/

Please update the script to check the current country's file, which contain much more mirrors, for example:
Brazil - http://mirrors.ubuntu.com/BR.txt
USA - http://mirrors.ubuntu.com/US.txt
France - http://mirrors.ubuntu.com/FR.txt

**Comment by jblakeman** [comment]
Thanks for reporting.  My guess is that this was either an unannounced deprecation or incidental recent change by the mirrors.ubuntu.com admins.  Perhaps the IP lookup database the server used to render the correct list by country is failing.

This pretty much breaks the tool.  The logical fix is just to parse https://launchpad.net/ubuntu/+archivemirrors or fetch the country lists as you've suggested, though I'm not sure of the most reliable way to choose the country.  I don't think we want to spawn 438 threads to test latency (total number of mirrors across all countries).  There's the file `/var/lib/mirrors/mirrors.ubuntu.com_mirrors.txt` we could look for but I don't think that would be reliable.

I'll try to do some research and take some time to fix this in the next week.  I've been busy with other things and haven't been able to maintain this tool much at all over the past year, but will try to make a concerted effort to fix this one given the urgency.

**Comment by imatimba** [comment]
You could use the lists with the country code creating a new argument to specify the country.  
I changed the mirror url on __main__.py to http://mirrors.ubuntu.com/US.txt and works fine.

**Comment by jblakeman** [comment]
I should have been more clear in the last comment. The problem I'm wondering about how to best solve is how would the default country be selected if none is provided via the command line?

**Comment by imatimba** [comment]
Make it mandatory or show a warning about it and default to US.  
I would go with making it mandatory. You could show the list of available countries and let the user pick if he doesn't specify it manually with the argument.

**Comment by jblakeman** [comment]
Perhaps a requirement is the best option. It certainly is a straight forward fix, but would be a breaking change.

One alternative I'm thinking about is to just test all mirrors regardless of country if no country is provided via the command line.  There'd have to be some considerations of the available memory (perhaps `psutil.virtual_memory().available`) vs. the calculated data size of all threads.  Once that's determined, thread sets could be split into chunks and joined in sequence to avoid overwhelming system memory by starting too many threads at once.

**Comment by jblakeman** [comment]
I'll start working on a fix that adds a country argument, defaulting to US if not provided.
