### ISSUE TITLE
UnicodeEncodeError when listing mirror info with unicode chars

### ISSUE THREAD

**Issue by jackm** [jblakeman/apt-select#67]
I got the following trace dump after running `apt-select --country CA -t 10 -m two-days-behind -l`:

```
Traceback (most recent call last):
  File "/usr/local/bin/apt-select", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/apt_select/__main__.py", line 236, in main
    apt_select()
  File "/usr/local/lib/python3.5/dist-packages/apt_select/__main__.py", line 188, in apt_select
    print_status(info, rank)
  File "/usr/local/lib/python3.5/dist-packages/apt_select/__main__.py", line 82, in print_status
    'speed': info['Speed']
UnicodeEncodeError: 'ascii' codec can't encode character '\u0142' in position 73: ordinal not in range(128)
```

This happens when it tries to encode the name of a mirror hosted by [Rafał Rzeczkowski](https://launchpad.net/ubuntu/+mirror/archive.ubuntu.mirror.rafal.ca-archive) (note the unicode character in the 5th position).
Seems related to #4; perhaps you missed a few places where it is still encoding/decoding in ascii rather than utf-8.

**Comment by jblakeman** [comment]
I'm unable to reproduce.  What is your environment's encoding?  You can see with `locale charmap`.  If not UTF-8 supported, you can set with something like `LANG=en_CA.utf8`.

**Comment by jackm** [comment]
My locale settings were indeed set to "POSIX"

```
user@server:~$ locale
LANG=
LANGUAGE=
LC_CTYPE="POSIX"
LC_NUMERIC="POSIX"
LC_TIME="POSIX"
LC_COLLATE="POSIX"
LC_MONETARY="POSIX"
LC_MESSAGES="POSIX"
LC_PAPER="POSIX"
LC_NAME="POSIX"
LC_ADDRESS="POSIX"
LC_TELEPHONE="POSIX"
LC_MEASUREMENT="POSIX"
LC_IDENTIFICATION="POSIX"
LC_ALL=
```

After setting them all to "en_CA.UTF-8", I don't get the UnicodeEncodeError.
