### ISSUE TITLE
Traceback on Ubuntu 17.10

### ISSUE THREAD

**Issue by sbrkopac** [jblakeman/apt-select#68]
I installed apt-select using the following:

`git clone https://github.com/jblakeman/apt-select.git
 sudo python apt-select/setup.py install`

I don't see any blatant errors when installing. When I attempt to invoke

`apt-select`

I get the attached trace back. I can transcribe it here if needed.
<img width="398" alt="traceback" src="https://user-images.githubusercontent.com/1939712/34177944-3ede479a-e4ba-11e7-8380-46d35c6c9506.PNG">

**Comment by jblakeman** [comment]
I think since you are installing the package as the superuser you are having problems when running while not the superuser.  Try `sudo apt-get install python-pip` -> `pip install apt-select` -> `apt-select`.

**Comment by jblakeman** [comment]
Alternatively, after running `sudo apt-get install python-pip` you can build from source using `python setup.py install`.

Adding this important setup step (installing `python-pip`) to the `README` could benefit users.
