### ISSUE TITLE
Breaks with FTP apt sources

### ISSUE THREAD

**Issue by Karunamon** [jblakeman/apt-select#7]
Greetings,

Just tried a run on a freshly upgraded Ubuntu 14.10. After installing the `python3-bs4` package, I run the program directly, and receive the following output:

    #python3 ./apt-select.py -l
    Getting list of mirrors ... done.
    Testing 66 mirror(s) [66/66] 100%
    Traceback (most recent call last):
        File "./apt-select.py", line 277, in <module>
            repo_name = match(r'http://([\w\.\-]+)/', repo[0]).group(1)
     AttributeError: 'NoneType' object has no attribute 'group'

My python is quite weak, but it looks as if the tool is having a hard time parsing my sources.list file. I think this is because the regex on line 277 expects the file to start with an `http://` deb source, but [my file](https://gist.github.com/Karunamon/8f7731c762b18226ddf9) is mostly FTPs. If that line is changed as:

`repo_name = match(r'(http://|ftp://)([\w\.\-]+)/', repo[0]).group(1)`

..then all works as expected.

**Comment by jblakeman** [comment]
Confirmed, ftp support should be included here.  I've decided it's a much simpler approach to use split to parse these urls over regex.

**Comment by jblakeman** [comment]
Fix issued in commit [35b25d9040](https://github.com/jblakeman/apt-select/commit/35b25d9040e122e7b295f69c35f004efe95691b7)
