### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 5: ordinal not in range(128)

### ISSUE THREAD

**Issue by dragonwt** [jblakeman/apt-select#71]
Selecting mirror http://www.mirrorservice.org/sites/archive.ubuntu.com/ubuntu/ ...
Traceback (most recent call last):
  File "/www/myenv/bin/apt-select", line 11, in <module>
    sys.exit(main())
  File "/www/myenv/local/lib/python2.7/site-packages/apt_select/__main__.py", line 244, in main
    apt_select()
  File "/www/myenv/local/lib/python2.7/site-packages/apt_select/__main__.py", line 233, in apt_select
    sources.generate_new_config(work_dir, new_mirror)
  File "/www/myenv/local/lib/python2.7/site-packages/apt_select/apt.py", line 177, in generate_new_config
    self.__set_config_lines(new_mirror)
  File "/www/myenv/local/lib/python2.7/site-packages/apt_select/apt.py", line 173, in __set_config_lines
    self._lines = self._lines.replace(url, new_mirror)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 5: ordinal not in range(128)

**Comment by jblakeman** [comment]
It seems the system's `locale` only supports ascii characters (e.g. empty `LANG`, `LANG=C`, `LANG=POSIX`) when there is a unicode character found in `/etc/apt/sources.list`. I believe official Ubuntu docker images are examples of systems where locale is configured to only support ascii by default.

Setting `LANG=C.UTF-8` in the environment should resolve it.

However, to support comments with unicode characters in `/etc/apt/sources.list`, I think we could easily fix it here by using the [`io` module](https://docs.python.org/2.7/library/io.html)'s `open` like:

```python
with io.open('/etc/apt/sources.list', encoding='utf-8') as f:
```

Then, encode the replaced string before writing it to the new file.

Related to #67, but different in that a fix should not require ignoring or replacing non ascii characters before trying to write to the console.

I'll note that this would not be an issue in Python 3.7 where [PEP 538](https://www.python.org/dev/peps/pep-0538/) is now implemented.

**Comment by dragonwt** [comment]
ok,solved,thank you.
