### ISSUE TITLE
Invalid country. latam is not in ISO 3166-1 alpha-2 format

### ISSUE THREAD

**Issue by fantapereira** [jblakeman/apt-select#74]
i have tried to run a nextcloud automated script. but everytime i choose my location (argentina) i got the error and the script fails 

Invalid country. latam is not in ISO 3166-1 alpha-2 format.

Even if i try to modify the keyboard layout and the timezone, it ended with the legend 
Invalid country. latam is not in ISO 3166-1 alpha-2 format

**Comment by jblakeman** [comment]
I believe the code you're looking for is [`AR`](https://en.wikipedia.org/wiki/ISO_3166-2:AR), not `latam`.

**Comment by fantapereira** [comment]
Yes, but every time i choose Buenos Aires or either another location, i got the same error.

The script automatically choose "latam" as a keyboard as you see here

**Current keyboard layout is latam**
/var/scripts/nextcloud-startup-script.sh: line 289: ask_yes_or_no: command not found
update-initramfs: deferring update (trigger activated)
Processing triggers for initramfs-tools (0.130ubuntu3.6) ...
update-initramfs: Generating /boot/initrd.img-4.15.0-43-generic

Current timezone is America/Argentina/Buenos_Aires
/var/scripts/nextcloud-startup-script.sh: line 301: ask_yes_or_no: command not found

Current default time zone: 'America/Argentina/Buenos_Aires'
Local time is now:      Mon Jan 21 18:41:48 -03 2019.
Universal Time is now:  Mon Jan 21 21:41:48 UTC 2019.
Checking current mirror...
Your current server repository is:
/var/scripts/nextcloud-startup-script.sh: line 319: ask_yes_or_no: command not found
Locating the best mirrors...
/var/scripts/nextcloud-startup-script.sh: line 325: spinner_loading: command not found
Reading package lists... Done
Building dependency tree
Reading state information... Done
python-pip is already the newest version (9.0.1-2.3~ubuntu1).
The following packages were automatically installed and are no longer required:
  linux-headers-4.15.0-29 linux-headers-4.15.0-29-generic linux-image-4.15.0-29-generic linux-modules-4.15.0-29-generic linux-modules-extra-4.15.0-29-generic
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
The directory '/home/ncadmin/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/ncadmin/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7fc207b73490>: Failed to establish a new connection: [Errno 101] Network is unreachable',)': /simple/pip/
Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7fc207b73610>: Failed to establish a new connection: [Errno 101] Network is unreachable',)': /simple/pip/
Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7fc207b73790>: Failed to establish a new connection: [Errno 101] Network is unreachable',)': /simple/pip/
Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7fc207b73910>: Failed to establish a new connection: [Errno 101] Network is unreachable',)': /simple/pip/
Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7fc207b73a90>: Failed to establish a new connection: [Errno 101] Network is unreachable',)': /simple/pip/
Requirement already up-to-date: pip in /usr/local/lib/python2.7/dist-packages (18.1)
Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7fc207b73790>: Failed to establish a new connection: [Errno 101] Network is unreachable',)': /simple/apt-select/
Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7fc207b73910>: Failed to establish a new connection: [Errno 101] Network is unreachable',)': /simple/apt-select/
Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7fc207b73b50>: Failed to establish a new connection: [Errno 101] Network is unreachable',)': /simple/apt-select/
Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7fc207b73650>: Failed to establish a new connection: [Errno 101] Network is unreachable',)': /simple/apt-select/
Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7fc207b73ad0>: Failed to establish a new connection: [Errno 101] Network is unreachable',)': /simple/apt-select/
Requirement already up-to-date: apt-select in /usr/local/lib/python2.7/dist-packages (2.1.0)
Requirement already satisfied, skipping upgrade: requests in /usr/local/lib/python2.7/dist-packages (from apt-select) (2.21.0)
Requirement already satisfied, skipping upgrade: beautifulsoup4 in /usr/local/lib/python2.7/dist-packages (from apt-select) (4.7.1)
Requirement already satisfied, skipping upgrade: urllib3<1.25,>=1.21.1 in /usr/local/lib/python2.7/dist-packages (from requests->apt-select) (1.24.1)
Requirement already satisfied, skipping upgrade: certifi>=2017.4.17 in /usr/local/lib/python2.7/dist-packages (from requests->apt-select) (2018.11.29)
Requirement already satisfied, skipping upgrade: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python2.7/dist-packages (from requests->apt-select) (3.0.4)
Requirement already satisfied, skipping upgrade: idna<2.9,>=2.5 in /usr/local/lib/python2.7/dist-packages (from requests->apt-select) (2.8)
Requirement already satisfied, skipping upgrade: soupsieve>=1.2 in /usr/local/lib/python2.7/dist-packages (from beautifulsoup4->apt-select) (1.7.2)
Requirement already satisfied, skipping upgrade: backports.functools-lru-cache; python_version < "3" in /usr/local/lib/python2.7/dist-packages (from soupsieve>=1.2->beautifulsoup4->apt-select) (1.5)
Invalid country. latam is not in ISO 3166-1 alpha-2 format
Sorry but something went wrong. Please report this issue to  and include the output of the error message. Thank you!
apt-select -m up-to-date -t 5 -c -C latam failed

**Comment by jblakeman** [comment]
@fantapereira I think you might be a bit confused. I did not author `/var/scripts/nextcloud-startup-script.sh` and so cannot support it. Please contact the authors of that script for support regarding it's incorrect automation of inferring an exact country code using your keyboard layout.

You'll see that the following works as expected if you run it with a correctly installed up to date version from the command line:

```
apt-select -m up-to-date -t 5 -c -C AR
```

Note the difference: `AR`, not `latam`.
