### ISSUE TITLE
2 consecutive err's in mirrors.py

### ISSUE THREAD

**Issue by gudzenkov** [jblakeman/apt-select#9]
$ apt-select/apt-select.py -t 10 -l
    Getting list of mirrors ... done.
    Testing 10 mirror(s) [10/10] 100%
    Looking up status(es) [0/9] 0%Traceback (most recent call last):
      File "apt-select/apt-select.py", line 217, in <module>
        flag_status
      File "/home/gudzenkov/scripts/apt-select/mirrors.py", line 121, in getInfo
        if "unknown" in status:
    TypeError: argument of type 'NoneType' is not iterable```

    $ apt-select/apt-select.py -t 10 -l
    Getting list of mirrors ... done.
    Testing 10 mirror(s) [10/10] 100%
    Looking up status(es) [0/3] 0%Traceback (most recent call last):
      File "apt-select/apt-select.py", line 217, in <module>
        flag_status
      File "/home/gudzenkov/scripts/apt-select/mirrors.py", line 106, in getInfo
        launch_html = urlopen(archive)
      File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
        return opener.open(url, data, timeout)
      File "/usr/lib/python2.7/urllib2.py", line 431, in open
        response = self._open(req, data)
      File "/usr/lib/python2.7/urllib2.py", line 449, in _open
        '_open', req)
      File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
        result = func(*args)
      File "/usr/lib/python2.7/urllib2.py", line 1240, in https_open
        context=self._context)
      File "/usr/lib/python2.7/urllib2.py", line 1197, in do_open
        raise URLError(err)
    urllib2.URLError: <urlopen error timed out>

###Mirrors list from mirrors.ubuntu.com/mirrors.txt :
http://kartolo.sby.datautama.net.id/ubuntu/
http://mirror.poliwangi.ac.id/ubuntu/
http://kebo.pens.ac.id/ubuntu/
http://jaran.undip.ac.id/ubuntu/
http://kambing.ui.ac.id/ubuntu/
http://suro.ubaya.ac.id/ubuntu/
http://buaya.klas.or.id/ubuntu/
http://mirror.unej.ac.id/ubuntu/
http://mirror.kavalinux.com/ubuntu/
http://archive.ubuntu.com/ubuntu/

###Mirror's status, Indonesia:
Kelompok Linux Arek Suroboyo	http ftp rsync	1 Gbps	One week behind
University of Indonesia	http ftp rsync	1 Gbps	One week behind
Datautama-Net-ID	http rsync	1 Gbps	Last update unknown
Politeknik Elektronika Negeri Surabaya	http ftp rsync	1 Gbps	One week behind
Universitas Jember	http ftp rsync	1 Gbps	Up to date
UPT Pusat Komputer Undip	http ftp rsync	100 Mbps	One week behind
kavalinux	http	100 Mbps	Up to date
Universitas Surabaya	http ftp rsync	100 Mbps	Last update unknown
State Polytechnic of Banyuwangi	http	10 Mbps	Last update unknown

**Comment by jblakeman** [comment]
Your `sources.list` file is not in the correct format.  For proper information on how to format a `sources.list` file, see [`man sources.list`](http://manpages.ubuntu.com/manpages/trusty/man5/sources.list.5.html).

**Comment by jblakeman** [comment]
You're likely getting `URLError` because launchpad was either down or refusing your connection.  When I originally wrote this, the `urllib`/`urllib2` error handling was implemented poorly in mirrors.py.  Expect a fix pushed soon.

**Comment by jblakeman** [comment]
Changed from bug to enhancement as this fix really just gives more easily diagnosable error output.
